skillMetadata:
    sections:
      - name: Options
        fields:
          - name: printeractive
            type: checkbox
            label: Printer is connected.
            value: "false"
          - name: printall
            type: checkbox
            label: Prints out everything Mycroft says when checked.
            value: "false"
          - name: printtime
            type: checkbox
            label: Print current date/time with message.
            value: "true"
          - name: printlf
            type: checkbox
            label: Adds a line feed after each message.
            value: "false"
          - name: bucketsize
            type: number
            label: How many past messages to keep?
            value: 50
      - name: USB Printer
        fields:
          - type: label
            label: Make sure to apply the udev rule and to add the local user to the lp group.
          - name: printdev
            type: text
            label: The local path (eg. /dev/usb/lp0).
            value: "/dev/usb/lp0"
  