skillMetadata:
    sections:
      - name: Options
        fields:
          - name: Print out everything?
            type: checkbox
            label: Prints out everything Mycroft says when checked.
            value: "false"
      - name: USB Printer
        fields:
          - name: printdev
            type: text
            label: The local path (eg. /dev/usb/lp0).
            value: "/dev/usb/lp0"
  