skillMetadata:
    sections:
      - name: Options
        fields:
          - name: printall
            type: checkbox
            label: Prints out everything Mycroft says when checked.
            value: "false"
          - name: bucketsize
            type: number
            label: How many past messages to keep?
            value: 50
      - name: USB Printer
        fields:
          - name: printdev
            type: text
            label: The local path (eg. /dev/usb/lp0).
            value: "/dev/usb/lp0"
  