skillMetadata:
    sections:
      - name: USB Printer
        fields:
          - name: printdev
            type: text
            label: The location of your USB attached printer (eg. /dev/usb/lp0).
            value: "/dev/usb/lp0"
  